name: Golang tests
run-name: Run go tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkuut repo
        uses: actions/checkout@v4
        
      - name: Run test with MakeFile
        run: make test