name: Golang tests
run-name: Run go tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkuut repo
        uses: actions/checkout@v4
      
      - name: Install/Check Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
       
        
      - name: Run test with MakeFile
        run: make test TEMPLATE_PATH=${{ github.workspace }}